name: foglamp
version: 0.1
summary: FogLAMP is the ultimate IoT solution stack.
description: FogLAMP is the ultimate IoT solution stack.
confinement: devmode
grade: devel

apps:
  foglamp:
       command: usr/bin/wrapper-foglamp
       plugs: [network]
  bash:
        command: bash
parts:
  gnu-bash:
        source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
        plugin: autotools
  foglamp-python-requirements:
    source: https://github.com/foglamp/FogLAMP.git
    requirements: python/requirements.txt
    plugin: python
    python-version: python3

  foglamp:
    source: https://github.com/foglamp/FogLAMP.git
    source-branch: develop
    build-packages:
        - cmake
        - g++
        - libpq-dev
        - libboost-dev
        - libboost-system-dev
        - libboost-thread-dev
    stage-packages:
        - curl
        - postgresql
    plugin: make
    install: |
      echo "unix_socket_directories = '/tmp'" >> $SNAPCRAFT_PART_INSTALL/usr/share/postgresql/9.5/postgresql.conf.sample
      cd $SNAPCRAFT_PART_INSTALL/usr/local/foglamp/plugins/storage/postgres ; ln -s ../../../../../lib/postgresql/9.5 $SNAPCRAFT_PART_INSTALL/usr/local/foglamp/plugins/storage/postgres/pgsql
      sed -i 's/"managed" : false/"managed" : true/g' $SNAPCRAFT_PART_INSTALL/usr/local/foglamp/data/etc/foglamp.json
  wrapper:
    after:
        - foglamp
    plugin: make
    source: .
                  
