name: foglamp
version: 1.1.1
summary: FogLAMP is the ultimate IoT solution stack.
description: FogLAMP is the ultimate IoT solution stack.
confinement: devmode
grade: devel

apps:
  foglamp:
       command: usr/bin/wrapper-foglamp
       plugs: [network]
  fogbench:
       command: usr/bin/wrapper-fogbench
       plugs: [network]
parts:
  foglamp-python-requirements:
    source: https://github.com/foglamp/FogLAMP.git
    source-branch: master
    requirements: python/requirements.txt
    plugin: python
    python-version: python3
    stage-packages:
        - python3-dbus

  foglamp:
    source: https://github.com/foglamp/FogLAMP.git
    source-branch: master
    build-packages:
        - cmake
        - g++
        - libpq-dev
        - libboost-dev
        - libboost-system-dev
        - libboost-thread-dev
        - python-dbus
    stage-packages:
        - curl
        - postgresql
        - bluez
    plugin: make
    install: |
      sed -i "$ a\unix_socket_directories = '/tmp'" $SNAPCRAFT_PART_INSTALL/usr/share/postgresql/*/postgresql.conf.sample
      cd $SNAPCRAFT_PART_INSTALL/usr/local/foglamp/plugins/storage/postgres ; ln -s ../../../../../lib/postgresql/* $SNAPCRAFT_PART_INSTALL/usr/local/foglamp/plugins/storage/postgres/pgsql
      sed -i 's/"managed" : false/"managed" : true/g' $SNAPCRAFT_PART_INSTALL/usr/local/foglamp/data/etc/foglamp.json
  wrapper:
    after:
        - foglamp
    plugin: make
    source: .
                  
