#!/bin/bash

set -e

# This variables must be set here
is_quiet=0  # When 0, it requires input and prints messagess

# First, check some of the arguments passed to the script
for argument  in "$@"
do
  lower_arg=`echo ${argument} | awk '{print tolower( $0 )}'`
  case "${lower_arg}" in
    silent)
      is_quiet=1
      ;;
    *)
      ;;
  esac
done

USAGE="Usage: `basename ${0}` {help|start|stop|init|restart|reload|kill|status|test} [silent]"

export FOGLAMP_ROOT=$SNAP/usr/local/foglamp/
export FOGLAMP_DATA=${SNAP_USER_COMMON}
export PYTHONPATH=$FOGLAMP_ROOT/python
POSTGRES_SOCKET_DIR=$FOGLAMP_DATA/storage/postgres
export DB_CONNECTION="dbname=foglamp host=${POSTGRES_SOCKET_DIR}"
POSTGRES_SYSTEM_DIR=$FOGLAMP_DATA/storage/postgres/pgsql
POSTGRES_DATA_DIR=${POSTGRES_SYSTEM_DIR}/data
POSTGRES_LOG_DIR=${POSTGRES_SYSTEM_DIR}/logs
POSTGRES_LOG_FILE=${POSTGRES_LOG_DIR}/logfile
POSTGRES_ROOT=$FOGLAMP_ROOT/plugins/storage/postgres/pgsql

# tablespace dir
#${FOGLAMP_DATA}/storage/postgres/PG_9.6_YYYYMMDDX

#PSQLHIST_DIR=${SNAP_USER_COMMON}/history

##
## Start the FogLAMP Storage Layer
##
storage_start() {
  if [ ${is_quiet} -eq 0 ]; then
    echo -n "Starting the FogLAMP Storage Layer..."
  fi
  if [ `${SNAP}/usr/bin/wrapper-pg_ctl -l ${POSTGRES_LOG_FILE} -D ${POSTGRES_DATA_DIR} status | grep -c "server is running"` -gt 0 ]; then

    if [ ${is_quiet} -eq 0 ]; then
      echo " It looks like the FogLAMP Storage Layer is already running."
    fi 

  else
    ${SNAP}/usr/bin/wrapper-pg_ctl -l ${POSTGRES_LOG_FILE} -D ${POSTGRES_DATA_DIR} start > /dev/null
    sleep 5
    cycle=120
    while [ "$cycle" -gt 0 ]; do
      if [ `${SNAP}/usr/bin/wrapper-pg_ctl -l ${POSTGRES_LOG_FILE} -D ${POSTGRES_DATA_DIR} status | grep -c "server is running"` -gt 0 ]; then
        if [ ${is_quiet} -eq 0 ]; then
          echo " Done."
        fi
        cycle=0
      else
        if [ "$cycle" -eq 1 ]; then
          echo "Error: the Storage Layer cannot start."
          exit 3
        else
          echo -n "."
          cycle=$((cycle -1))
          sleep 1
        fi
      fi
    done

  fi
}

##
## Stop the FogLAMP Storage Layer
##
storage_stop() {
  if [ ${is_quiet} -eq 0 ]; then
    echo -n "Stopping the FogLAMP Storage Layer..."
  fi

  ${SNAP}/usr/bin/wrapper-pg_ctl -l ${POSTGRES_LOG_FILE} -D ${POSTGRES_DATA_DIR} stop > /dev/null

  cycle=30
  while [ "$cycle" -gt 0 ]; do
    if [ `${SNAP}/usr/bin/wrapper-pg_ctl -l ${POSTGRES_LOG_FILE} -D ${POSTGRES_DATA_DIR} status | grep -c "no server running"` -gt 0 ]; then
      if [ ${is_quiet} -eq 0 ]; then
        echo " Done."
      fi
      cycle=0
    else
      if [ "$cycle" -eq 1 ]; then
        echo " The FogLAMP Storage Layer cannot be stopped. Try with the command 'foglamp kill'."
        exit 3
      else
        echo -n "."
        cycle=$((cycle -1))
        sleep 1
      fi
    fi
  done
}

##
## Start FogLAMP
##
foglamp_start() {
  storage_start
  $FOGLAMP_ROOT/bin/foglamp start
}

##
## Initialize FogLAMP
##
foglamp_init() {
  rm -rf ${FOGLAMP_DATA}/*
  mkdir -p ${POSTGRES_SOCKET_DIR} ${POSTGRES_SYSTEM_DIR} ${POSTGRES_DATA_DIR} ${POSTGRES_LOG_DIR}
  ${SNAP}/usr/bin/wrapper-initialize initdb
  echo "unix_socket_directories='${POSTGRES_SOCKET_DIR}'" >> ${POSTGRES_DATA_DIR}/postgresql.conf
  # TODO: storage sometimes needs a few seconds to fully start
  storage_start
  ${SNAP}/usr/bin/wrapper-psql -h ${POSTGRES_SOCKET_DIR} -d postgres -f $FOGLAMP_ROOT/plugins/storage/postgres/init.sql > /dev/null
  storage_stop
}

##
## Check the status of FogLAMP
##
foglamp_status() {
  ${SNAP}/bin/foglamp status
}

##
## Stop FogLAMP
##
foglamp_stop() {
  ${SNAP}/bin/foglamp stop
  storage_stop
}

case "$1" in
  help)
    foglamp_help
    ;;
  start)
    foglamp_start
    ;;
  init)
    foglamp_init
    ;;
  status)
    foglamp_status
    ;;
#  test)
#    foglamp_test test
#    ;;
  stop)
    foglamp_stop
    ;;
#  kill)
#    foglamp_stop kill
#    ;;
  restart|reload|condrestart)
    foglamp_stop
    sleep 5
    foglamp_start
    ;;
  *)
    echo "${USAGE}"
    exit 1
esac

exit $?
