#!/bin/sh

set -e

export PSQLRC="$SNAP_USER_COMMON/.psqlrc"
export FOGLAMP_ROOT=$SNAP/usr/local/foglamp/
export POSTGRES_ROOT=$FOGLAMP_ROOT/plugins/storage/postgres/usr

$POSTGRES_ROOT/bin/psql "$@"
