#!/bin/sh

set -e

#
# Locale configuration
#
export I18NPATH=$SNAP/usr/share/i18n
export LOCPATH=$SNAP_USER_DATA/locales
export FOGLAMP_ROOT=$SNAP/usr/local/foglamp/
export FOGLAMP_DATA=${SNAP_USER_COMMON}
export PYTHONPATH=$FOGLAMP_ROOT/python
POSTGRES_SOCKET_DIR=$FOGLAMP_DATA/storage/postgres
export DB_CONNECTION="dbname=foglamp host=${POSTGRES_SOCKET_DIR}"
POSTGRES_SYSTEM_DIR=$FOGLAMP_DATA/storage/postgres/pgsql
POSTGRES_DATA_DIR=${POSTGRES_SYSTEM_DIR}/data
POSTGRES_LOG_DIR=${POSTGRES_SYSTEM_DIR}/logs
POSTGRES_LOG_FILE=${POSTGRES_LOG_DIR}/logfile
POSTGRES_ROOT=$FOGLAMP_ROOT/plugins/storage/postgres/pgsql
export LD_LIBRARY_PATH=$POSTGRES_ROOT/lib:$LD_LIBRARY_PATH


LOCLANG=en_US
LOCEN=UTF-8
LOC="$LOCLANG.$LOCEN"

export LANG=$LOC

$POSTGRES_ROOT/bin/pg_ctl "$@"
