#!/bin/sh

set -e

#
# Locale configuration
#
export I18NPATH=$SNAP/usr/share/i18n
export LOCPATH=$SNAP_USER_DATA/locales
export FOGLAMP_ROOT=$SNAP/usr/local/foglamp/
export POSTGRES_ROOT=$FOGLAMP_ROOT/plugins/storage/postgres/usr


LOCLANG=en_US
LOCEN=UTF-8
LOC="$LOCLANG.$LOCEN"

export LANG=$LOC

$POSTGRES_ROOT/bin/pg_ctl "$@"
